parameters:
    # Blog contact email address
    abuchyn_alex.emails.contacts_email: abuchyn@gmail.com

    # Default path for upload images
    images_directory: '%kernel.root_dir%/../web/uploads/title_images'